---
- name: Create systemd mount units
  ansible.builtin.copy:
    content: "{{ item.value }}"
    dest: "/etc/systemd/system/{{ item.key }}.mount"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ systemd_mounts | dict2items }}"

- name: Enable systemd mount units
  ansible.builtin.systemd_service:
    name: "{{ item.key }}.mount"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ systemd_mounts | dict2items }}"
