---
- name: Validate keepalived config
  ansible.builtin.command:
    cmd: keepalived --config-test

- name: Restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    enabled: true
    state: restarted
    daemon_reload: true

