---
- name: Create /etc/nginx/nginx.conf
  ansible.builtin.copy:
    content: "{{ nginx_conf }}"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart nginx
