---
- name: Create /etc/apache2/conf-enabled
  ansible.builtin.file:
    path: /etc/apache2/conf-enabled
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Define variable
  ansible.builtin.set_fact:
    _apache2_conf_enabled: {}

- name: Define symlinks to apache2 configuration snippets
  ansible.builtin.set_fact:
    _apache2_conf_enabled: "{{ _apache2_conf_enabled | combine({ '/etc/apache2/conf-enabled/' ~ item: '../conf-available/' ~ item }) }}"
  loop: "{{ apache2_conf_enabled }}"

- name: Find existing symlinks to apache2 configuration snippets
  ansible.builtin.find:
    paths: /etc/apache2/conf-enabled
    file_type: link
  register: symlinks

- name: Remove unwanted symlinks to apache2 configuration snippets
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  when: item.path not in _apache2_conf_enabled
  loop: "{{ symlinks.files }}"
  notify:
    - Restart apache2
  
- name: Find files in /etc/apache2/conf-enabled
  ansible.builtin.find:
    paths: /etc/apache2/conf-enabled
  register: files

- name: Remove files from /etc/apache2/conf-enabled
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ files.files }}"
  notify:
    - Restart apache2
  
- name: Create symlinks to apache2 configuration snippets
  ansible.builtin.file:
    src: "{{ item.value }}"
    dest: "{{ item.key }}"
    state: link
  loop: "{{ _apache2_conf_enabled | dict2items }}"
  notify:
    - Restart apache2
