---
- name: Create /etc/apache2/ports.conf
  ansible.builtin.copy:
    content: "{{ apache2_ports }}"
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart apache2
